# Generated by Django 4.2.1 on 2023-06-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_is_active',
            field=models.BooleanField(default=False, verbose_name='активная версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=100, verbose_name='название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
