# Generated by Django 4.2.1 on 2023-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_version_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_publicated',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
